### PR TITLE
Add Katello 4.10

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@pcreech does this look good?

**Comment by chris1984** [comment]
@ekohl does this look fine for a merge? The only thing I was not sure about was the GPG key

**Review by pcreech — APPROVED** [review]

**Comment by ianballou** [comment]
@pcreech the updated PR is here: https://github.com/theforeman/tool_belt/pull/558

**Comment by ianballou** [comment]
This can be closed now that https://github.com/theforeman/tool_belt/pull/558 is merged.

**Pull request closed without merging**
