### PR TITLE
Add corrections from running command to 2.1 and 3.16

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
How would you see it in the procedure? Besides a line that says review better Eric :)

**Comment by ekohl** [comment]
That, or at least specifically note that `based_on` should be filled in when copying nightly.

**Comment by ehelms** [comment]
Updated and added more procedure updates from my experience

**Comment by zjhuntin** [comment]
Needs a rebase

**Comment by ekohl** [comment]
Yes, I decided to merge https://github.com/theforeman/tool_belt/pull/207 rather than keeping it open for a long time.

**Pull request merged**
