### PR TITLE
Katello pulpcore mash config

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by evgeni** [comment]
where is the config that generated that? :)

**Comment by evgeni** [comment]
or is that straight from https://github.com/theforeman/tool_belt/blob/master/configs/katello/nightly.yaml unmodified?

**Comment by pcreech** [comment]
.. it was hand created :D ....  Missed the fact that we had generators for it

**Comment by pcreech** [comment]
@evgeni updated

**Comment by evgeni** [comment]
the generated file looks like what I would expect to to look like

**Pull request merged**
