### PR TITLE
Remove individual checkboxes for tagging and signing

### PR DESCRIPTION
**Pull request by ekohl**
These steps are usually ran rather atomically and indivual checkboxes are too much. It still keeps multiple lines because there are multiple scripts.

### CODE REVIEW

**Comment by ehelms** [comment]
As someone who recently did this process and hit errors in parts of these, I appreciate having the individual check boxes as a way to check off each individual step and remind myself where I am at if I get interrupted.

**Comment by ekohl** [comment]
Should we then go the other direction and remove the checkbox from the top, while leaving the individual ones? So `Tag the projects` and `Sign Tarballs`.

**Comment by ehelms** [comment]
> Should we then go the other direction and remove the checkbox from the top, while leaving the individual ones? So `Tag the projects` and `Sign Tarballs`.

Yes, I usually do find the top level checkbox a bit redundant when there are individual ones.

**Comment by ekohl** [comment]
I didn't touch some project branching since https://github.com/theforeman/tool_belt/pull/516 will rewrite that. For packaging branching I'm working on a rewrite as well where I move Katello packaging branching from Katello's branching procedure to Foreman's procedure.

**Pull request merged**
